title: Gêisson Machado Antunes
description: Meu blog pessoal sobre tecnologia e nerdices afins
author: Gêisson Machado Antunes
logo: http://aboutashu.com/hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/geison20
about: Desenvolvedor | Freelancer
disqus_shortname: aboutashu
google_analytics: UA-72862926-1
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about/
      icon: fa-comments
    - text: Projects
      url: /projects/
      icon: fa-desktop
    - text: Resume
      url: '#'
      icon: fa-graduation-cap
    - text: Github
      url: https://github.com/geison20
      icon: fa-github
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed
      target: _blank

social:
    - icon: fa-facebook
      link: '#'
    - icon: fa-skype
      link: '#'
    - icon: fa-twitter
      link: '#'
    - icon: fa-linkedin
      link: '#'
    - icon: fa-stack-exchange
      link: '#'

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: "http://geissonmachado.com.br/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
