
# meta tags
title: Blog de tecnologia
description: Meu blog pessoal sobre ferramentas e tecnologias
author: Gêisson Machado Antunes
keywords:
  - "tag,"
  - "tag1"
charset: utf-8
language: "pt-br"

# perfil
logo: http://aboutashu.com/hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/geison20
about: Desenvolvedor e Freelancer
disqus_shortname: aboutashu
google_analytics: UA-72862926-1
urls:
    - text: Home #texto
      url: / #url
      icon: fa-home #fa icon
      layout: post #layout
    - text: Sobre
      url: /sobre/
      icon: fa-comments
    - text: Projetos
      url: /projetos/
      icon: fa-desktop
    - text: Resume
      url: '#'
      icon: fa-graduation-cap
    - text: Github
      url: https://github.com/geison20
      icon: fa-github
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed
      target: _blank

social:
    - icon: fa-facebook
      link: '#'
    - icon: fa-skype
      link: '#'
    - icon: fa-twitter
      link: '#'
    - icon: fa-linkedin
      link: '#'
    - icon: fa-stack-exchange
      link: '#'

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

url: "http://geissonmachado.com.br"
baseurl: "/blog"
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
