
#SEO -meta
language: pt-br
title-site: Blog de tecnologia e afins
description: Blog pessoal cheio de notícias, artigos e fontes relacionados a desenvolvimento de softwares e muito mais!
author: Gêisson Machado Antunes
email: geisonnm@hotmail.com
baseurl: ""
url:   "http://geissonmachado.com.br" #"http://localhost:4000" "http://geissonmachado.com.br" # the base hostname & protocol for your site

google-analytics: UA-82745983-1

# Build settings
markdown: kramdown
excerpt_separator: <!-- leia-mais --> # usado para quebar a description inicial do post
timezone: America/Sao_Paulo

# Assets directory
css: /static/css/style.css
css-min: /static/css/final/all.min.css
js-min: /static/js/final/app.js
image: /static/image/final/

# Gems
gems: [jekyll-paginate]

#pagination
paginate: 4
paginate_path: "/posts/pagina:num/"

# header configuration
site-name-header: Gêisson Machado Antunes
site-description-header: Devoloper | Mobile | Application | SEO
perfil-icon: http://www.portalworkbook.com.br/static/admin/img/img_perfil.jpg
social-icons:
  - icon: github
    link: github/
    icon-path: fa fa-github-square fa-2x
  - icon: linkedin
    link: linkedin/
    icon-path: fa fa-linkedin-square fa-2x
  - icon: facebook
    link: facebook/
    icon-path: fa fa-facebook-square fa-2x
  - icon: RSS
    link: http://www.geissonmachado.com.br/feed.xml
    icon-path: fa fa-rss-square fa-2x
